service: B1ime # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  environment: ${file(./env/${opt:stage}.yml)}

package:
  artifact: dst.zip

functions:
  api:
    handler: api.hello
    events:
      - http:
          method: get
          path: /