service: B1ime # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  environment: ${file(./env/${opt:stage, 'dev'}.yml)}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"

plugins:
  - serverless-offline
  - serverless-dynamodb-local

package:
  artifact: dst.zip

functions:
  login:
    handler: dst/api/users.login
    events:
      - http:
          method: post
          path: /login
  hello:
    handler: dst/api.hello
    events:
      - http:
          method: get
          path: /
  test:
    handler: dst/api.test
    events:
      - http:
          method: get
          path: /test
  createRoom:
    handler: dst/api/room.createRoom
    events:
      - http:
          method: post
          path: /room
  getRoomList:
    handler: dst/api/room.getRoomList
    events:
      - http:
          method: get
          path: /room

resources:
  Resources:
    B1imeTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: B1imeTable
        AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: name
          AttributeType: S
        KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: name
          KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    Room:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: Room
        AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true